{{- if eq (include "apply-open-telemetry-crs" . | trim) "true" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-otel-crs
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3 
  template:
    spec:
      serviceAccountName: otel-cr-applier
      containers:
      - name: apply-crs
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "⏳ Waiting for Operator pod..."
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=opentelemetry-operator,app.kubernetes.io/component=controller-manager -n {{ .Release.Namespace }} --timeout=120s
          echo "✅ Operator is ready. Applying CRs..."
          kubectl apply -f /crs/otel-collector.yaml -n {{ .Release.Namespace }}
          kubectl apply -f /crs/instrumentation.yaml -n {{ .Release.Namespace }}
        volumeMounts:
        - name: crs
          mountPath: /crs
      restartPolicy: Never
      volumes:
      - name: crs
        configMap:
          name: otel-crs
      {{- if or .Values.tolerations .Values.global.tolerations }}
      tolerations:
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.affinity .Values.global.affinity }}
      affinity:
        {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}         
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-crs
data:
  otel-collector.yaml: |-
{{ tpl (.Files.Get "files/randoli-otel/opentelemetry-collector.yaml") . | nindent 4 }}
  instrumentation.yaml: |-
{{ tpl (.Files.Get "files/randoli-otel/instrumentation.yaml") . | nindent 4 }}
{{end}}             
---