{{- if eq (include "apply-open-telemetry-crs" . | trim) "true" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-cr-applier
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: post-install,pre-delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-otel-cr-applier-role
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: post-install,pre-delete
rules:
- apiGroups: ["opentelemetry.io"]
  resources: ["opentelemetrycollectors", "targetallocators", "instrumentations"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-cr-applier-binding
  annotations:
    helm.sh/hook-weight: "-4"
    helm.sh/hook: post-install,pre-delete
subjects:
- kind: ServiceAccount
  name: otel-cr-applier
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-otel-cr-applier-role
  apiGroup: rbac.authorization.k8s.io
{{end}}
