{{- if ne .Values.global.proxySecretFile "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.proxySecretName }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    kubescape.io/ignore: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  proxy.crt: {{ .Values.global.proxySecretFile | quote }}
{{- end }}
