{{- $components := fromYaml (include "components" .) }}
{{- if $components.otelCollector.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: otel-collector-config
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.global.cloudConfig "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  otel-collector-config.yaml: |-
{{ tpl (.Files.Get "assets/otel-collector-config.yaml") . | indent 4 }}
{{- end }}
