{{- $components := fromYaml (include "components" .) }}
{{- if $components.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.otelCollector.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.otelCollector.name) | nindent 4 }}
{{ end }}
