apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pixie-operator-subscription
  namespace: {{ default .Release.Namespace .Values.olmOperatorNamespace }}
spec:
  channel: {{ .Values.olmBundleChannel }}
  name: pixie-operator
  source: pixie-operator-index
  sourceNamespace: {{ default .Release.Namespace .Values.olmOperatorNamespace }}
  installPlanApproval: Automatic
