apiVersion: batch/v1
kind: Job
metadata:
  name: delete-otel-crs
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: otel-cr-applier
      containers:
      - name: apply-crs
        image: bitnami/kubectl:latest
        command:
        - /bin/bash
        - -c
        - |
          echo "⏳ Deleting Otel CRs..."
          kubectl delete opentelemetrycollector randoli-otel -n {{ .Release.Namespace }}
          kubectl delete instrumentation otel-instrumentation -n {{ .Release.Namespace }}          
        volumeMounts:
        - name: crs
          mountPath: /crs
      restartPolicy: Never
      volumes:
      - name: crs
        configMap:
          name: otel-crs
---
