apiVersion: batch/v1
kind: Job
metadata:
  name: randoli-otel-remove-finalizer
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  #backoffLimit: 1
  #activeDeadlineSeconds: 60
  #ttlSecondsAfterFinished: 30
  template:
    spec:
      serviceAccountName: opentelemetry-operator
      containers:
        - name: finalizer-remover
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch opentelemetrycollectors.opentelemetry.io randoli-otel \
                -n {{ .Release.Namespace }} \
                --type=json \
                -p='[{"op": "remove", "path": "/metadata/finalizers"}]'
      restartPolicy: OnFailure

           