apiVersion: v1
kind: ServiceAccount
metadata:
  name: randoli-otel-collector
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: randoli-otel-collector-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: randoli-otel-collector-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: randoli-otel-collector
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: randoli-otel-collector-clusterrole
  apiGroup: rbac.authorization.k8s.io