apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app-insights-agent.fullname" . }}-crb
  labels:
    {{- include "labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "app-insights-agent.serviceAccountName" . }}
    namespace: {{ include "app-insights-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "app-insights-agent.fullname" . }}-role
