apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "randoli-agent.fullname" . }}-crb
  labels:
    {{- include "labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "randoli-agent.serviceAccountName" . }}
    namespace: {{ include "randoli-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "randoli-agent.fullname" . }}-role
