apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "randoli-agent.fullname" . }}-config
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  AGENT_CONTROLLER_DIAL_TIMEOUT: 10000ms
  APP_NAME: randoli-agent
  CLIENT_CERT_PATH: /app/certs/client-cert.pem
  CLIENT_PRIVATE_KEY_PATH: /app/certs/client-key.pem
  CONTEXT_PATH: /
  DEBUG: 'false'
  HTTP_SERVICE_PORT: '8080'
  KEYCLOAK_TIMEOUT: 1m0s
  {{- if .Values.global.opencost.url }}
  OPENCOST_BACKEND_URL: {{ .Values.global.opencost.url }}
  {{ else }}
  OPENCOST_BACKEND_URL: http://randoli-cmk-opencost.{{ .Release.Namespace }}.svc:9003
  {{ end -}}
  {{- if .Values.global.prometheus.install }}
  PROMETHEUS_URL: 'http://randoli-prometheus.{{ .Release.Namespace }}.svc:80'
  {{ else }}
  PROMETHEUS_URL: {{ .Values.global.prometheus.url }}
  {{ end -}}
  PROMETHEUS_INSECURE_SKIP_VERIFY: {{ .Values.global.prometheus.tlsInsecureSkipVerify | quote }}
  TLS_ENABLED: 'true'
  RIGHTSIZING_RECOMMENDATIONS_ENABLED: '{{ .Values.tags.costManagement }}'
  RIGHTSIZING_INSTALL_VPA: '{{ include "enable.vpa.operator" . }}'
  SECURITY_SCANS_MODE: '{{ include "observability.secutiry.mode" . }}'
  SECURITY_SCANS_CRON_SPEC: '{{ .Values.observability.security.cronSpec }}'
  SECURITY_SCANS_INSTALL_KUBESCAPE: '{{ include "enable.security" . }}'
  COLLECT_LOGS: '{{ .Values.logs.shipLogSamples.enabled }}'
  ENABLE_DEFAULT_TIMELINE_PROMETHEUS_QUERIES: '{{ .Values.anomalyDetection.defaultsQueries.enabled }}'
  PROMETHEUS_CUSTOM_QUERIES_PATH: '{{ .Values.anomalyDetection.customQueries.path }}'
  OPENCOST_INSTALL: '{{ .Values.tags.costManagement }}'
  IMAGE_REGISTRY: '{{ .Values.image.registry }}'
  IMAGE_REPOSITORY: '{{ .Values.image.repository }}'
  IMAGE_TAG: '{{ .Values.image.tag }}'
  IMAGE_DIGEST: '{{ .Values.image.digest }}'
  IMAGE_PULL_POLICY: '{{ .Values.image.pullPolicy }}'
  RESOURCES_LIMITS_CPU: '{{ .Values.resources.limits.cpu }}'
  RESOURCES_LIMITS_MEMORY: '{{ .Values.resources.limits.memory }}'
  RESOURCES_REQUESTS_CPU: '{{ .Values.resources.requests.cpu }}'
  RESOURCES_REQUESTS_MEMORY: '{{ .Values.resources.requests.memory }}'
  PIXIE_INSTALL: '{{ include "enable.pixie.operator" .}}'
  LOG_ANALYZERS_ENABLED: '{{ .Values.logs.analyzers.enabled }}'
  VECTOR_INSTALL: '{{ include "enable.vector" . }}'
  VECTOR_HTTP_SINKER_URL: 'http://{{ include "randoli-agent.fullname" . }}.{{ include "randoli-agent.namespace" . }}:8080/log-sink/'
  PROMETHEUS_INSTALL: '{{ .Values.global.prometheus.install }}'
  TEKTON_PIPELINE_ENABLED: '{{ .Values.tektonPipeline.enabled }}'
  JAEGER_QUERY_SVC_GRPC: randoli-rok-jaeger-query.{{ .Release.Namespace }}:16685
  JAEGER_QUERY_SVC_HTTP: http://randoli-rok-jaeger-query.{{ .Release.Namespace }}:16686
  PROMETHEUS_ALERTMANAGER_URL: http://{{ .Release.Name }}-alertmanager.{{ .Release.Namespace }}:9093
