apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "randoli-agent.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
