apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "randoli-agent.fullname" . }}
  annotations:
    # Keep the PVC (and the data it holds) on helm uninstall; users delete
    # it manually if no longer needed.
    helm.sh/resource-policy: keep
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  {{- if .Values.agent.storageClassName }}
  storageClassName: {{ .Values.agent.storageClassName | quote }}
  {{- end}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.agent.db.storage.pvSize }}
  volumeMode: Filesystem
