apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-{{ include "randoli-agent.fullname" . }}-rb
  namespace: {{ include "randoli-agent.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "randoli-agent.serviceAccountName" . }}
    namespace: {{ include "randoli-agent.namespace" . }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-{{ include "randoli-agent.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
