apiVersion: v1
kind: Service
metadata:
  name: randoli-agent
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: agent
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: gizmosql
      protocol: TCP
      port: 31337
      targetPort: 31337  
  selector:
    app.kubernetes.io/name: {{ include "randoli-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-agent
  type: ClusterIP
