apiVersion: v1
kind: Service
metadata:
  name: {{ include "randoli-agent.fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "randoli-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-agent
  type: ClusterIP
