{{- /*
Randoli agent deployment using a statefulset
*/ -}}
{{- $dbCredsSecretName := printf "%s-db" (include "randoli-agent.fullname" .) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "randoli-agent.fullname" . }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "randoli-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-agent
    {{- include "labels" . | nindent 4 }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.agent.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    resource.opentelemetry.io/service.name: randoli-agent
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.agent.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "randoli-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: randoli-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "randoli-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: randoli-agent
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.agent.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.global.annotations .Values.agent.annotations }}
      annotations:
        {{- with .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.agent.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.global.secrets.cert }}
            items:
              - key: client-cert.pem
                path: client-cert.pem
              - key: client-key.pem
                path: client-key.pem
            defaultMode: 420
        {{- if and .Values.global.prometheus.tlsCertConfigmapName .Values.global.prometheus.tlsCertConfigmapKey }}
        - name: prometheus-tls-cert
          configMap:
            name: {{ .Values.global.prometheus.tlsCertConfigmapName }}
            items:
              - key: {{ .Values.global.prometheus.tlsCertConfigmapKey }}
                path: prometheus-service.crt
        {{- end }}
        {{- if .Values.agent.extraVolumes }}
          {{- toYaml .Values.agent.extraVolumes | nindent 8}}
        {{- end }}

      containers:
        - name: randoli-agent
          {{- with .Values.agent.image }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}{{- if (.digest) -}} @{{ .digest }}{{- else -}}:{{ default $.Chart.AppVersion .tag }} {{- end -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - |
              echo "Waiting for the FlightSQL server to be ready..."
              while ! nc -z {{ include "agent-db-host" . }} 31337; do
                sleep 1
              done
              echo "Starting agent..."
              exec /app/cluster-agent
          command:
            - /bin/sh
            - -c
          envFrom:
            - secretRef:
                name: {{ .Values.global.secrets.config }}
            - configMapRef:
                name: {{ include "randoli-agent.fullname" . }}-config
            {{- if .Values.agent.extraEnvFrom }}
              {{- toYaml .Values.agent.extraEnvFrom | nindent 12 }}
            {{- end }}
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tls-certs
              mountPath: /app/certs
            {{- if and .Values.global.prometheus.tlsCertConfigmapName .Values.global.prometheus.tlsCertConfigmapKey }}
            - mountPath: /etc/ssl/certs/prometheus-service.crt
              name: prometheus-tls-cert
              subPath: prometheus-service.crt
              readOnly: false
            {{- end }}
            {{- if .Values.agent.extraVolumeMounts }}
              {{- toYaml .Values.agent.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: FLIGHT_SQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $dbCredsSecretName }}
                  key: username
            - name: FLIGHT_SQL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ $dbCredsSecretName }}
                  key: password
          {{- if or .Values.agent.extraEnv .Values.global.prometheus.secretName }}
            {{- if and .Values.global.prometheus.secretName .Values.global.prometheus.usernameKey }}
            - name: PROMETHEUS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.prometheus.secretName }}
                  key: {{ .Values.global.prometheus.usernameKey }}
            {{- end }}
            {{- if and .Values.global.prometheus.secretName .Values.global.prometheus.passwordKey }}
            - name: PROMETHEUS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.prometheus.secretName }}
                  key: {{ .Values.global.prometheus.passwordKey }}
            {{- else if and .Values.global.prometheus.secretName .Values.global.prometheus.bearerTokenKey }}
            - name: PROMETHEUS_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.prometheus.secretName }}
                  key: {{ .Values.global.prometheus.bearerTokenKey }}
            {{- end }}
            {{- if .Values.agent.extraEnv }}
              {{- toYaml .Values.agent.extraEnv | nindent 12 }}
            {{- end }}
          {{- end }}
      serviceAccountName: {{ template "randoli-agent.serviceAccountName" . }}
      serviceAccount: {{ template "randoli-agent.serviceAccountName" . }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.agent.tolerations .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.agent.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.agent.affinity .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}