apiVersion: v2
name: vertical-pod-autoscaler
description: Randoli wrapper chart for Kubernetes VPA (v0.8.1)
type: application
version: 0.8.1
appVersion: "1.6.0"
dependencies:
  - name: vertical-pod-autoscaler
    version: 0.8.1
    repository: https://kubernetes.github.io/autoscaler
