{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: "v1beta1.spdx.softwarecomposition.kubescape.io"
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.storage.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  group: "spdx.softwarecomposition.kubescape.io"
  groupPriorityMinimum: 1000
  versionPriority: 15
  version: "v1beta1"
  service:
    name: {{ .Values.storage.name }}
    namespace: {{ include "randoli-agent.namespace" . }}
  {{- if .Values.storage.mtls.enabled }}
  caBundle: {{ .Values.global.storageCA.Cert | b64enc }}
  {{- else }}
  insecureSkipTLSVerify: true
  {{- end }}
{{- end }}
