{{- if .Values.storage.mtls.enabled }}
{{- $ca := include "storage.generateCerts.ca" . | fromJson }}
{{- $cert := include "storage.generateCerts.cert" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storage.name }}-ca
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.storage.name "tier" .Values.global.namespaceTier) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
