{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ include "storage.authDelegatorClusterRoleBindingName" . | quote }}
  labels:
    kubescape.io/ignore: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ .Values.storage.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.storage.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.storage.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.storage.name }}
    namespace: {{ include "randoli-agent.namespace" . }}
{{- end }}
