{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-{{ include "storage.authReaderRoleBindingName" . }}
  namespace: kube-system
  labels:
    kubescape.io/ignore: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # This is a default role name provided by K8s and should not be templated or changed
  name: "extension-apiserver-authentication-reader"
subjects:
- kind: ServiceAccount
  name: {{ .Values.storage.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
{{- end }}
