{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "storage.authReaderRoleBindingName" . | quote }}
  namespace: kube-system
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.storage.name "tier" .Values.global.namespaceTier) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  # This is a default role name provided by K8s and should not be templated or changed
  name: "extension-apiserver-authentication-reader"
subjects:
- kind: ServiceAccount
  name: {{ .Values.storage.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
{{- end }}
