{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "storage.fullname" . }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    kubescape.io/ignore: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    {{ .Values.storage.labels | toYaml | nindent 4 }}
{{- end }}
