{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.storage.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.storage.name "tier" .Values.global.namespaceTier) | nindent 4 }}
{{- end }}
