{{- $components := fromYaml (include "components" .) }}
{{- if $components.storage.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.storage.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    kubescape.io/ignore: "true"
{{- end }}
