apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tproxy-role-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tproxy-role
subjects:
  - kind: ServiceAccount
    name: tproxy
    namespace: {{ include "randoli-agent.namespace" . }}