apiVersion: v1
kind: ConfigMap
metadata:
  name: randoli-tproxy
  namespace: {{ include "randoli-agent.namespace" . }}
data:
  LOKI_BASE_URL: {{ include "logs-loki-read-url" . }}
  LISTEN_ADDR: ':8080'
  ROUTE_PREFIX: /api/loki
  ENABLE_CORS: 'true'
  CORS_ALLOW_ORIGIN: {{ include "telemetry-proxy-cors" . }}
  KEYCLOAK_ISSUER_URL: {{ include "telemetry-proxy-keycloak-issuer" . }}
  TEMPO_BASE_URL: {{ include "trace-storage-url" . }}
  PROMETHEUS_BASE_URL: {{ include "prometheus-server-endpoint" . }}
  {{- with .Values.tproxy.tunnelServerUrl }}
  TUNNEL_SERVER_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.tproxy.mode }}
  MODE: {{ . | quote }}
  {{- end }}
  {{- if .Values.tproxy.otel.enabled }}
  OTEL_ENABLED: 'true'
  OTEL_TRACE_SAMPLE_RATIO: '{{ .Values.tproxy.otel.traceSampleRatio }}'
  {{- if .Values.tproxy.otel.exporterOtlpEndpoint }}
  OTEL_EXPORTER_OTLP_ENDPOINT: '{{ .Values.tproxy.otel.exporterOtlpEndpoint }}'
  {{- else }}
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://randoli-otel-collector.{{ .Release.Namespace }}.svc:4317'
  {{- end }}
  {{- else }}
  OTEL_ENABLED: 'false'
  {{- end }}
  FLIGHT_SQL_HOST: '{{ .Values.tproxy.flightSql.host | default (printf "randoli-agent.%s.svc:31337" (include "randoli-agent.namespace" .)) }}'
