apiVersion: apps/v1
kind: Deployment
metadata:
  name: randoli-tproxy
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: randoli-tproxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: randoli-tproxy
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.tproxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    resource.opentelemetry.io/service.name: randoli-tproxy
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.tproxy.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: randoli-tproxy
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: randoli-tproxy
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: randoli-tproxy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: randoli-tproxy
        {{- with .Values.global.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tproxy.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.global.annotations .Values.tproxy.annotations }}
      annotations:
        {{- with .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tproxy.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
        - name: randoli-tproxy
          {{- with .Values.tproxy.image }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}:{{ .tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.tproxy.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secrets.config }}
                  key: CLUSTER_ID    
          envFrom:
            - configMapRef:
                name: randoli-tproxy
          resources:
            limits:
              cpu: 200m
              memory: "512Mi"
            requests:
              cpu: 30m
              memory: "128Mi"
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.tproxy.tolerations .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.tproxy.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with coalesce .Values.tproxy.affinity .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
