apiVersion: v2
name: opentelemetry-operator
description: Randoli wrapper chart for the OpenTelemetry Operator (v0.86.4)
type: application
version: 0.111.0
appVersion: "0.149.0"
dependencies:
  - name: opentelemetry-operator
    version: 0.111.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
