{{- $components := fromYaml (include "components" .) }}
{{- if $components.nodeAgent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeAgent.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  ports:
  - name: prometheus
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.nodeAgent.name) | nindent 4 }}
{{- end }}
