{{ if .Values.olmOperatorNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.olmOperatorNamespace }}
{{ end }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: {{ default .Release.Namespace .Values.olmOperatorNamespace }}
