apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: netobserv-operator
    control-plane: controller-manager
  name: netobserv-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: netobserv-operator
    control-plane: controller-manager
status:
  loadBalancer: {}
