apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netobserv-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: netobserv-leader-election-role
subjects:
  - kind: ServiceAccount
    name: netobserv-controller-manager
    namespace: '{{ .Release.Namespace }}'
