{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevuln.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kubevuln.fullname" . }}
  labels:
    kubescape.io/ignore: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubevuln.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubevuln.fullname" . }}
  namespace: {{ include "randoli-agent.namespace" . }}
{{- end }}
