{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevuln.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
{{- if .Values.cloudProviderMetadata.awsIamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cloudProviderMetadata.awsIamRoleArn }}
  {{- else if .Values.cloudProviderMetadata.gkeServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.cloudProviderMetadata.gkeServiceAccount }}
{{- end }}
  labels:
    app: {{ .Values.kubevuln.name }}
    kubescape.io/ignore: "true"
  name: {{ .Values.kubevuln.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
automountServiceAccountToken: false
{{- end }}
