{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: host-scanner-definition
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.global.cloudConfig "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  host-scanner-yaml: |-
{{ tpl (.Files.Get "assets/host-scanner-definition.yaml") . | indent 4 }}
{{- end }}
