{{- $components := fromYaml (include "components" .) }}
{{- if and .Values.global.networkPolicy.enabled $components.kubescape.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescape.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescape.name) | nindent 6 }}
  policyTypes:
    - Ingress
  {{- if .Values.global.networkPolicy.createEgressRules }}
    - Egress
  egress:
      # - backend api server
      # - GitRegoStore (https://github.com/kubescape/regolibrary/releases/)
    - ports:
        - port: 443
          protocol: TCP
      # Cloud Vendor detection (Instance Metadata Services)
    - ports:
        - port: 80
          protocol: TCP
      to:
        - ipBlock:
            cidr: 169.254.169.254/32
{{ tpl (.Files.Get "assets/api-server-egress-rules.yaml") . | indent 4 }}
{{ tpl (.Files.Get "assets/common-egress-rules.yaml") . | indent 4 }}
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name) | nindent 14 }}
      ports:
        - port: http
          protocol: TCP
{{ end }}
