{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    kubescape.io/ignore: "true"
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "get", "update", "watch", "list", "patch", "delete"]
{{ end }}
