{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescape.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  type: {{ .Values.kubescape.service.type }}
  ports:
    - name: http
      port: {{ .Values.kubescape.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescape.name) | nindent 6 }}
{{ end }}
