{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubescape.fullname" . }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app: {{ template "kubescape.fullname" . }}
    kubescape.io/ignore: "true"
spec:
  type: {{ .Values.kubescape.service.type }}
  ports:
    - name: http
      port: {{ .Values.kubescape.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ template "kubescape.fullname" . }}
{{ end }}
