{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescape.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubescape.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.kubescape.name }}
    kubescape.io/ignore: "true"
spec:
  type: {{ .Values.kubescape.service.type }}
  ports:
    - name: http
      port: {{ .Values.kubescape.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.kubescape.name }}
{{ end }}
