{{- $components := fromYaml (include "components" .) }}
{{- if $components.autoUpdater.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.helmReleaseUpgrader.name "tier" .Values.global.namespaceTier) | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Values.helmReleaseUpgrader.name }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.helmReleaseUpgrader.name "tier" .Values.global.namespaceTier) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.helmReleaseUpgrader.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.helmReleaseUpgrader.name }}
{{ end }}
