apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  name: flowmetric-cluster-external-egress-traffic
  namespace: netobserv
spec:
  charts:
    - dashboardName: Main
      queries:
        - legend: ''
          promQL: sum(rate($METRIC[2m]))
          top: 7
      title: External egress traffic
      type: SingleStat
      unit: Bps
    - dashboardName: Main
      queries:
        - legend: '{{SrcK8S_Namespace}} / {{SrcK8S_OwnerName}}'
          promQL: >-
            sum(rate($METRIC{SrcK8S_Namespace!=""}[2m])) by (SrcK8S_Namespace,
            SrcK8S_OwnerName)
          top: 7
      sectionName: External
      title: Top external egress traffic per workload
      type: StackArea
      unit: Bps
  direction: Egress
  filters:
    - field: DstSubnetLabel
      matchType: Absence
  labels:
    - SrcK8S_Name
    - SrcK8S_Type
    - SrcK8S_Namespace
    - SrcK8S_OwnerName
    - DstAddr
  metricName: cluster_external_egress_bytes_total
  type: Counter
  valueField: Bytes
