apiVersion: flows.netobserv.io/v1beta2
kind: FlowCollector
metadata:
  name: cluster
  annotations:
    "helm.sh/hook": post-install, post-upgrade
spec:
  namespace: netobserv
  consolePlugin:
    advanced:
      env:
        TEST_CONSOLE: "true"
  prometheus:
    querier:
      manual:
        url: {{ include "prometheus-server-endpoint" . }}
  loki:
    enable: false
  exporters:
  - type: OpenTelemetry
    openTelemetry:
      targetHost: "randoli-otel-collector.{{ .Release.Namespace }}.svc.cluster.local"
      targetPort: 4317
      protocol: grpc
      logs:
        enable: false
      metrics:
        enable: true