{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.prometheusExporter.name }}
  labels:
    kubescape.io/ignore: "true"
rules:
  - apiGroups: ["spdx.softwarecomposition.kubescape.io"]
    resources: ["configurationscansummaries", "vulnerabilitysummaries"]
    verbs: ["get", "watch", "list"]
{{- end }}
