{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ .Values.prometheusExporter.name }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.prometheusExporter.name "tier" .Values.global.namespaceTier) | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Values.prometheusExporter.name }}
{{- end }}
