{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
{{- $no_proxy_envar_list := (include "no_proxy_envar_list" .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.prometheusExporter.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Values.prometheusExporter.name }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.prometheusExporter.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.prometheusExporter.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        tier: {{ .Values.global.namespaceTier }}
        app: {{ .Values.prometheusExporter.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      securityContext:
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: {{ .Values.prometheusExporter.name }}
          image: {{ .Values.prometheusExporter.image.repository }}:{{ .Values.prometheusExporter.image.tag }}
          imagePullPolicy: {{ .Values.prometheusExporter.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          ports:
          - name: metrics
            containerPort: {{ .Values.prometheusExporter.service.port }}
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.prometheusExporter.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.prometheusExporter.service.port }}
          resources:
{{ toYaml .Values.prometheusExporter.resources | indent 12 }}
          env:
            - name: GOMEMLIMIT
              value: "{{ .Values.prometheusExporter.resources.requests.memory }}B"
            - name: KS_LOGGER_LEVEL
              value: "{{ .Values.logger.level }}"
            - name: KS_LOGGER_NAME
              value: "{{ .Values.logger.name }}"
          volumeMounts:
            - name: {{ .Values.global.cloudConfig }}
              mountPath: /etc/config
              readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 12 }}
{{- end }}
{{- if .Values.kubevuln.volumeMounts }}
{{ toYaml .Values.kubevuln.volumeMounts | indent 12 }}
{{- end }}
      volumes:
        - name: {{ .Values.global.cloudConfig }}
          configMap:
            name: {{ .Values.global.cloudConfig }}
            items:
            - key: "clusterData"
              path: "clusterData.json"
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
{{- if .Values.prometheusExporter.volumes }}
{{ toYaml .Values.prometheusExporter.volumes | indent 8 }}
{{- end }}
      serviceAccountName: {{ .Values.prometheusExporter.name }}
      automountServiceAccountToken: true
      {{- if or .Values.prometheusExporter.tolerations .Values.customScheduling.tolerations .Values.global.tolerations }}
      tolerations:
        {{- with .Values.prometheusExporter.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.prometheusExporter.nodeSelector .Values.customScheduling.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- with .Values.prometheusExporter.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.prometheusExporter.affinity .Values.customScheduling.affinity .Values.global.affinity }}
      affinity:
        {{- with .Values.prometheusExporter.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
{{- end }}
