{{- $components := fromYaml (include "components" .) }}
{{- if and .Values.global.networkPolicy.enabled $components.prometheusExporter.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.prometheusExporter.name }}
    tier: {{ .Values.global.namespaceTier }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.prometheusExporter.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.prometheusExporter.service.port }}
          protocol: TCP
{{- end }}
