{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
kind: ServiceAccount
apiVersion: v1
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
{{- if .Values.cloudProviderMetadata.awsIamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cloudProviderMetadata.awsIamRoleArn }}
  {{- else if .Values.cloudProviderMetadata.gkeServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.cloudProviderMetadata.gkeServiceAccount }}
{{- end }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.prometheusExporter.name "tier" .Values.global.namespaceTier) | nindent 4 }}
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
automountServiceAccountToken: false
{{- end }}
