{{- $components := fromYaml (include "components" .) }}
{{- if $components.prometheusExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.prometheusExporter.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.prometheusExporter.name }}
spec:
  namespaceSelector:
    matchNames:
      -  {{ include "app-insights-agent.namespace" . }}
  selector:
    matchLabels:
      app: {{ .Values.prometheusExporter.name }}
{{ end }}
