- ports:
    - port: 53
      protocol: UDP
  to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
- ports:
    - port: 4317
      protocol: TCP
    - port: 4318
      protocol: TCP
  to:
    - podSelector:
        matchLabels:
          {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.otelCollector.name) | nindent 10 }}
{{- if ne .Values.global.httpsProxy "" }}
- ports:
    - port: {{ .Values.global.networkPolicy.httpsProxyPort }}
      protocol: TCP
  to:
    - ipBlock:
        cidr: {{ .Values.global.networkPolicy.httpsProxyIP }}/32
{{- end }}
