apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: {{ .Values.kubevulnScheduler.name }}
      namespace: {{ include "randoli-agent.namespace" . }}
      labels:
        app: {{ .Values.kubevulnScheduler.name }}
        kubescape.io/ignore: "true"
        kubescape.io/tier: "core"
        tier: {{ .Values.global.namespaceTier }}
        armo.tier: "vuln-scan"
    spec:
      schedule: "{{ .Values.kubevulnScheduler.scanSchedule }}" 
      successfulJobsHistoryLimit: {{ .Values.kubevulnScheduler.successfulJobsHistoryLimit }}
      failedJobsHistoryLimit: {{ .Values.kubevulnScheduler.failedJobsHistoryLimit }}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                armo.tier: "vuln-scan"
                kubescape.io/tier: "core"
            spec:
            {{- if .Values.imagePullSecrets }}
              imagePullSecrets:
              - name: {{ toYaml .Values.imagePullSecrets }}
            {{- end }}
              containers:
              - name: {{ .Values.kubevulnScheduler.name }}
                image: "{{ .Values.kubevulnScheduler.image.repository }}:{{ .Values.kubevulnScheduler.image.tag }}"
                imagePullPolicy: {{ .Values.kubevulnScheduler.image.pullPolicy }}
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 100
                resources:
{{ toYaml .Values.kubevulnScheduler.resources | indent 18 }}
                args: 
                  - -method=post
                  - -scheme=http
                  - -host={{ .Values.operator.name }}:{{ .Values.operator.service.port }}
                  - -path=v1/triggerAction
                  - -headers=Content-Type:application/json
                  - -path-body=/home/ks/request-body.json
                volumeMounts:
                  - name: "request-body-volume"
                    mountPath: /home/ks/request-body.json
                    subPath: request-body.json
                    readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 18 }}
{{- end }}
{{- if .Values.kubevulnScheduler.volumeMounts }}
{{ toYaml .Values.kubevulnScheduler.volumeMounts | indent 18 }}
{{- end }}
              restartPolicy: Never
              automountServiceAccountToken: false

              
              {{- if or .Values.kubevulnScheduler.tolerations .Values.customScheduling.tolerations .Values.global.tolerations }}
              tolerations:
                {{- with .Values.kubevulnScheduler.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              {{- if or .Values.kubevulnScheduler.nodeSelector .Values.customScheduling.nodeSelector .Values.global.nodeSelector }}
              nodeSelector:
                {{- with .Values.kubevulnScheduler.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              {{- if or .Values.kubevulnScheduler.affinity .Values.customScheduling.affinity .Values.global.affinity }}
              affinity:
                {{- with .Values.kubevulnScheduler.affinity }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.affinity }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.affinity }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              volumes:
                - name: "request-body-volume" # placeholder
                  configMap:
                    name: {{ .Values.kubevulnScheduler.name }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 16 }}
{{- end }}
{{- if .Values.kubevulnScheduler.volumes }}
{{ toYaml .Values.kubevulnScheduler.volumes | indent 16 }}
{{- end }}
