apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: {{ .Values.registryScanScheduler.name }}
      namespace: {{ include "randoli-agent.namespace" . }}
      labels:
        app: {{ .Values.registryScanScheduler.name }}
        kubescape.io/tier: "core"
        tier: {{ .Values.global.namespaceTier }}
        armo.tier: "registry-scan"
    spec:
      schedule: "{{ .Values.registryScanScheduler.scanSchedule }}"
      successfulJobsHistoryLimit: {{ .Values.registryScanScheduler.successfulJobsHistoryLimit }}
      failedJobsHistoryLimit: {{ .Values.registryScanScheduler.failedJobsHistoryLimit }}
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                armo.tier: "registry-scan"
                kubescape.io/tier: "core"
            spec:
              securityContext:
                seccompProfile:
                  type: RuntimeDefault
              {{- if .Values.imagePullSecrets }}
              imagePullSecrets:
              {{- if kindIs "string" .Values.imagePullSecrets }}
              - name: {{ .Values.imagePullSecrets }}
              {{- else }}
              {{- range .Values.imagePullSecrets }}
              - name: {{ . }}
              {{- end }}
              {{- end }}
              {{- end }}
              containers:
              - name: {{ .Values.registryScanScheduler.name }}
                image: "{{ .Values.registryScanScheduler.image.repository }}:{{ .Values.registryScanScheduler.image.tag }}"
                imagePullPolicy: {{ .Values.registryScanScheduler.image.pullPolicy }}
                securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  runAsNonRoot: true
                  runAsUser: 100
                resources:
{{ toYaml .Values.registryScanScheduler.resources | indent 18 }}
                args:
                  - -method=post
                  - -scheme=http
                  - -host={{ .Values.operator.name }}:{{ .Values.operator.service.port }}
                  - -path=v1/triggerAction
                  - -headers=Content-Type:application/json
                  - -path-body=/home/ks/request-body.json
                {{- if .Values.registryScanScheduler.insecureSkipTLSVerify }}
                  - -skip-ssl-verify=true
                {{- end}}
                volumeMounts:
                  - name: "request-body-volume"
                    mountPath: /home/ks/request-body.json
                    subPath: request-body.json
                    readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 18 }}
{{- end }}
{{- if .Values.registryScanScheduler.volumeMounts }}
{{ toYaml .Values.registryScanScheduler.volumeMounts | indent 18 }}
{{- end }}
              restartPolicy: Never
              serviceAccountName: {{ .Values.kubevuln.name }}
              automountServiceAccountToken: false
              {{- if or .Values.registryScanScheduler.tolerations .Values.customScheduling.tolerations .Values.global.tolerations }}
              tolerations:
                {{- with .Values.registryScanScheduler.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              {{- if or .Values.registryScanScheduler.nodeSelector .Values.customScheduling.nodeSelector .Values.global.nodeSelector }}
              nodeSelector:
                {{- with .Values.registryScanScheduler.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.nodeSelector }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              {{- if or .Values.registryScanScheduler.affinity .Values.customScheduling.tolerations .Values.global.affinity }}
              affinity:
                {{- with .Values.registryScanScheduler.affinity }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.customScheduling.tolerations }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.global.affinity }}
                {{- toYaml . | nindent 16 }}
                {{- end }} 
              {{- end }}
              volumes:
                - name: "request-body-volume" # placeholder
                  configMap:
                    name: {{ .Values.registryScanScheduler.name }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 16 }}
{{- end }}
{{- if .Values.registryScanScheduler.volumes }}
{{ toYaml .Values.registryScanScheduler.volumes | indent 16 }}
{{- end }}
