{{- if .Values.grypeOfflineDB.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grypeOfflineDB.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ .Values.grypeOfflineDB.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Values.grypeOfflineDB.name }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.grypeOfflineDB.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier }}
  template:
    metadata:
      labels:
        kubescape.io/tier: "core"
        app.kubernetes.io/name: {{ .Values.grypeOfflineDB.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        tier: {{ .Values.global.namespaceTier }}
        app: {{ .Values.grypeOfflineDB.name }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ toYaml .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Values.grypeOfflineDB.name }}
          image: "{{ .Values.grypeOfflineDB.image.repository }}@{{ .Values.grypeOfflineDB.image.sha }}"
          imagePullPolicy: {{ .Values.grypeOfflineDB.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
{{ toYaml .Values.grypeOfflineDB.resources | indent 12 }}
      {{- if or .Values.grypeOfflineDB.tolerations .Values.customScheduling.tolerations .Values.global.tolerations }}
      tolerations:
        {{- with .Values.grypeOfflineDB.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.grypeOfflineDB.nodeSelector .Values.customScheduling.nodeSelector .Values.global.nodeSelector }}
      nodeSelector:
        {{- with .Values.grypeOfflineDB.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
      {{- if or .Values.grypeOfflineDB.affinity .Values.customScheduling.affinity .Values.global.affinity }}
      affinity:
        {{- with .Values.grypeOfflineDB.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.customScheduling.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.global.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }} 
      {{- end }}
{{- end }}
