{{- if .Values.grypeOfflineDB.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grypeOfflineDB.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.grypeOfflineDB.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.grypeOfflineDB.name) | nindent 4 }}
{{- end }}
