{{- if .Values.grypeOfflineDB.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grypeOfflineDB.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.grypeOfflineDB.name }}
    kubescape.io/ignore: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.grypeOfflineDB.name }}
{{- end }}
