{{- if eq (include "apply-network-crs" . | trim) "true" -}}
apiVersion: v1
kind: ServiceAccount
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
metadata:
  name: network-cr-applier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-network-cr-applier-role
rules:
- apiGroups: ["flows.netobserv.io"]
  resources: ["flowmetrics", "flowcollectors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-cr-applier-binding
subjects:
- kind: ServiceAccount
  name: network-cr-applier
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-network-cr-applier-role
  apiGroup: rbac.authorization.k8s.io
{{end}}