{{- if .Values.config.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: randoli-alerts-cm-applier
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-alerts-cm-applier-role
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
- verbs: ["get", "delete"]
  apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["{{ include "alertmanager.fullname" . }}"]
- verbs: ["create"]
  apiGroups: [""]
  resources: ["configmaps"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: randoli-alerts-cm-applier-binding
  annotations:
    helm.sh/hook-weight: "-4"
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
- kind: ServiceAccount
  name: randoli-alerts-cm-applier
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-alerts-cm-applier-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}  

