{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubescapeScheduler.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.kubescapeScheduler.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubescapeScheduler.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  request-body.json: |-
    {{- .Values.kubescapeScheduler.requestBody | toJson | nindent 4 }}
{{- end }}
