apiVersion: v2
appVersion: '1.17'
description: Randoli Agent
home: https://randoli.ca
icon: https://s3.ca-central-1.amazonaws.com/randoli.ca/icons/icon-384x384.png
keywords:
- randoli-agent
- randoli
maintainers:
- name: Randoli
  url: https://randoli.ca
  email: support@randoli.ca
name: randoli-agent
sources:
- https://github.com/randoli/helm-charts
version: 1.17.7
dependencies:
  - name: opentelemetry-operator
    version: 0.86.4
    condition: observability.otel.operator.enabled
    tags:
     - observability
     - costManagement
  - name: prometheus
    version: 26.0.1
    condition: global.prometheus.install
  - name: rightsizing
    version: 1.0.0
    condition: costManagement.vpaOperator.enabled
    tags:
     - costManagement
  - name: security-scans
    alias: securityScans
    version: 1.29.6
    condition: observability.security.enabled
    tags:
     - security
  - name: logs
    version: 0.0.40
    condition: observability.vector.enabled
    tags:
     - observability
  - name: cost-management
    version: 1.42.0
    alias: costManagement
    tags:
     - costManagement
  - name: tracing
    version: 3.4.0
    condition: observability.tracing.enabled
    tags:
     - observability
  - name: network
    version: 1.8.2
    condition: observability.netobserv.enabled
    tags:
    - observability     
    - costManagement
