apiVersion: v2
name: cost-management
description: Randoli wrapper chart for OpenCost (v1.42.0)
type: application
version: 1.42.0
appVersion: "1.115.1"
dependencies:
  - name: opencost
    version: 1.42.0
    repository: https://opencost.github.io/opencost-helm-chart
