{{- $components := fromYaml (include "components" .) }}
{{- if $components.serviceDiscovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceDiscovery.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    kubescape.io/ignore: "true"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "0"
{{- end }}
