{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevulnScheduler.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.kubevulnScheduler.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubevulnScheduler.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  request-body.json: |-
    {"commands":[{"commandName":"scan","designators":[{"designatorType":"Attributes","attributes":{}}]}]}
{{- end }}
