{{- if not (.Capabilities.APIVersions.Has "batch/v1") }}
  {{- fail "`batch/v1 not supported`" }}
{{- end }}
{{- $components := fromYaml (include "components" .) }}
{{- if $components.kubevulnScheduler.enabled }}
{{- $kubevuln_daily_scan_cron_tab := (include "kubevuln_daily_scan_cron_tab" .) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.kubevulnScheduler.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubevulnScheduler.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    armo.tier: "vuln-scan"
    kubescape.io/tier: "core"
spec:
  schedule: "{{ trimPrefix "\n" (trimSuffix  "\n" $kubevuln_daily_scan_cron_tab) }}"
  successfulJobsHistoryLimit: {{ .Values.kubevulnScheduler.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.kubevulnScheduler.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 12 }}
            {{- with .Values.kubevulnScheduler.podAnnotations }}{{- toYaml . | nindent 12 }}{{- end }}
          labels:
            {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.kubevulnScheduler.name "tier" .Values.global.namespaceTier) | nindent 12 }}
            {{- with .Values.kubevulnScheduler.podLabels }}{{- toYaml . | nindent 12 }}{{- end }}
            armo.tier: "vuln-scan"
            kubescape.io/tier: "core"
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- if kindIs "string" .Values.imagePullSecrets }}
          - name: {{ .Values.imagePullSecrets }}
          {{- else }}
          {{- range .Values.imagePullSecrets }}
          - name: {{ . }}
          {{- end }}
          {{- end }}
          {{- end }}
          containers:
          - name: {{ .Values.kubevulnScheduler.name }}
            image: "{{ .Values.kubevulnScheduler.image.repository }}:{{ .Values.kubevulnScheduler.image.tag }}"
            imagePullPolicy: {{ .Values.kubevulnScheduler.image.pullPolicy }}
            resources:
{{ toYaml .Values.kubevulnScheduler.resources | indent 14 }}
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 100
            args:
              - -method=post
              - -scheme=http
              - -host={{ .Values.operator.name }}:{{ .Values.operator.service.port }}
              - -path=v1/triggerAction
              - -headers=Content-Type:application/json
              - -path-body=/home/ks/request-body.json
            {{- if .Values.kubevulnScheduler.insecureSkipTLSVerify }}
              - -skip-ssl-verify=true
            {{- end}}
            volumeMounts:
              - name: {{ .Values.kubevulnScheduler.name }}
                mountPath: /home/ks/request-body.json
                subPath: request-body.json
                readOnly: true
{{- if .Values.volumeMounts }}
{{ toYaml .Values.volumeMounts | indent 14 }}
{{- end }}
{{- if .Values.kubevulnScheduler.volumeMounts }}
{{ toYaml .Values.kubevulnScheduler.volumeMounts | indent 14 }}
{{- end }}
          restartPolicy: Never
          serviceAccountName: {{ .Values.kubevuln.name }}
          automountServiceAccountToken: false
          {{- if or .Values.kubevulnScheduler.tolerations  .Values.customScheduling.tolerations .Values.global.tolerations }}
          tolerations:
            {{- with .Values.kubevulnScheduler.tolerations  }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.customScheduling.tolerations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.tolerations }}
            {{- toYaml . | nindent 12 }}
            {{- end }} 
          {{- end }}
          {{- if or .Values.kubevulnScheduler.nodeSelector .Values.customScheduling.nodeSelector .Values.global.nodeSelector }}
          nodeSelector:
            {{- with .Values.kubevulnScheduler.nodeSelector }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.customScheduling.nodeSelector }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.nodeSelector }}
            {{- toYaml . | nindent 12 }}
            {{- end }} 
          {{- end }}
          {{- if or .Values.kubevulnScheduler.affinity .Values.customScheduling.affinity .Values.global.affinity }}
          affinity:
            {{- with .Values.kubevulnScheduler.affinity }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.customScheduling.affinity }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.affinity }}
            {{- toYaml . | nindent 12 }}
            {{- end }} 
          {{- end }}
          volumes:
          - name: {{ .Values.kubevulnScheduler.name }}
            configMap:
              name: {{ .Values.kubevulnScheduler.name }}
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 10 }}
{{- end }}
{{- if .Values.kubevulnScheduler.volumes }}
{{ toYaml .Values.kubevulnScheduler.volumes | indent 10 }}
{{- end }}
{{- end }}
