{{- if .Values.telemetry.pixie.install }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: otel-collector
    {{- include "labels" . | nindent 4 }}
data:
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
    processors:
      batch:
      memory_limiter:
        # 80% of maximum memory up to 2G
        limit_mib: 1000
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 100
    exporters:
      logging:
        loglevel: info 
        sampling_initial: 5
        sampling_thereafter: 200
        # Data sources: metrics
      prometheus:
        endpoint: 0.0.0.0:8889
        metric_expiration: 1m
    service:
      extensions: [zpages, memory_ballast]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging, prometheus]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: otel-collector
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
  - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: prometheus
    port: 8889
    protocol: TCP
    targetPort: 8889
  selector:
    app.kubernetes.io/component: otel-collector
---
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor" -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: otel-collector
    {{- include "labels" . | nindent 4 }}
  name: otel-collector
  namespace: {{ include "app-insights-agent.namespace" . }}
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      port: prometheus
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
  selector:
    matchLabels:
      app.kubernetes.io/component: otel-collector
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: opentelemetry
    app.kubernetes.io/component: otel-collector
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry
      app.kubernetes.io/component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 # adjust this to your own requirements
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetry
        app.kubernetes.io/component: otel-collector
        {{- include "labels" . | nindent 8 }}
    spec:
      containers:
      - command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        image: otel/opentelemetry-collector:0.48.0
        name: otel-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55679 # Default endpoint for ZPages.
        - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
        - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
        - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
        - containerPort: 9411 # Default endpoint for Zipkin receiver.
        - containerPort: 8888  # Default endpoint for querying metrics.
        - containerPort: 8889  # Export metrics in open telemetry format/ Prometheus.
        volumeMounts:
        - name: otel-collector-config-vol
          mountPath: /conf
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol
{{ end }}