{{ if or .Values.enableSatelliteAgents .Values.awsMarketplace }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "app-insights-satellite-agent.name" . }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "app-insights-satellite-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-insights-agent
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app-insights-satellite-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: app-insights-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app-insights-satellite-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: app-insights-agent
    spec:
      containers:
        - name: app-insights-satellite
          {{- with .Values.satelliteImage }}
          image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}{{- if (.digest) -}} @{{ .digest }}{{- else -}}:{{ default $.Chart.AppVersion .tag }} {{- end -}}"
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "app-insights-satellite-agent.name" . }}-config
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 64Mi
      terminationGracePeriodSeconds: 30
      serviceAccountName: {{ template "app-insights-agent.serviceAccountName" . }}
      serviceAccount: {{ template "app-insights-agent.serviceAccountName" . }}
{{end}}