apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-insights-agent.fullname" . }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "app-insights-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-insights-agent
    {{- include "labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc-server
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: {{ include "app-insights-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-insights-agent