{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
{{- if eq .Values.capabilities.admissionController "enable" }}
apiVersion: v1
kind: Service
metadata:
  name: "kubescape-admission-webhook"
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name) | nindent 6 }}
  type: ClusterIP  # Or use LoadBalancer or NodePort if needed
{{- end }}
{{- end }}
