{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
{{- if eq .Values.capabilities.admissionController "enable" }}
{{- $svcName := (printf "kubescape-admission-webhook.%s.svc" (include "randoli-agent.namespace" .)) -}}
{{- $certData := fromYaml (include "admission-certificates" .) -}}
{{- $ca := $certData.ca -}}
{{- $cert := $certData.cert -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $svcName }}-kubescape-tls-pair
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
webhooks:
  - name: validation.kubescape.admission
    clientConfig:
      service:
        name: kubescape-admission-webhook
        namespace: {{ include "randoli-agent.namespace" . }}
        path: /validate
        port: 443
      caBundle: {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE", "CONNECT"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources: ["pods", "pods/exec", "pods/portforward", "pods/attach", "clusterrolebindings", "rolebindings"]
        scope: "*"
    failurePolicy: Ignore
{{- end }}
{{- end }}
