{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
{{- if not (.Capabilities.APIVersions.Has "batch/v1") }}
  {{- fail "`batch/v1 not supported`" }}
{{- end }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubescape-cronjob-template
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.global.cloudConfig "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/kubescape-cronjob-full.yaml") . }}
{{- end }}
