{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
{{- if not (.Capabilities.APIVersions.Has "batch/v1") }}
  {{- fail "`batch/v1 not supported`" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.global.cloudConfig "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
  name: registry-scan-cronjob-template
data:
  cronjobTemplate: |-
    {{ tpl (.Files.Get "assets/registry-scan-cronjob-full.yaml") . }}
{{- end }}
