{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
spec:
  type: {{ .Values.operator.service.type }}
  ports:
    - port: {{ .Values.operator.service.port }}
      targetPort: {{ .Values.operator.service.targetPort }}
      protocol: {{ .Values.operator.service.protocol }}
  selector:
    {{- include "kubescape-operator.selectorLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name) | nindent 6 }}
{{- end }}
