{{- $components := fromYaml (include "components" .) }}
{{- if $components.operator.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
{{- if .Values.cloudProviderMetadata.awsIamRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.cloudProviderMetadata.awsIamRoleArn }}
  {{- else if .Values.cloudProviderMetadata.gkeServiceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.cloudProviderMetadata.gkeServiceAccount }}
{{- end }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.operator.name "tier" .Values.global.namespaceTier) | nindent 4 }}
  name: {{ .Values.operator.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
automountServiceAccountToken: false
{{- end }}
