apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-manifests-applier
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: pre-install,post-delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-agent-manifests-applier-role
  annotations:
    helm.sh/hook-weight: "-5"
    helm.sh/hook: pre-install,post-delete
rules:
- verbs: ["create"]
  apiGroups: [""]
  resources: ["secrets"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "randoli-agent.fullname" . }}-db"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-manifests-applier-binding
  annotations:
    helm.sh/hook-weight: "-4"
    helm.sh/hook: pre-install,post-delete
subjects:
- kind: ServiceAccount
  name: agent-manifests-applier
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-agent-manifests-applier-role
  apiGroup: rbac.authorization.k8s.io
