{{- $secretName := printf "%s-db" (include "randoli-agent.fullname" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  username: {{ "admin" | b64enc }}
  password: >
    {{- if $existing }}
      {{ index $existing.data "password" }}
    {{- else }}
      {{ randAlphaNum 32 | b64enc }}
    {{- end }}