{{- $components := fromYaml (include "components" .) }}
{{- if .Values.global.overrideDefaultCaCertificates.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $components.customCaCertificates.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" $components.customCaCertificates.name "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/infra: credentials
type: Opaque
data:
  ca-certificates.crt: "{{ .Values.global.overrideDefaultCaCertificates.caCertificates | default "" | b64enc }}"
{{- end }}
