kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.continuousScanning.configMapName }}
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.ksLabel "tier" .Values.global.namespaceTier) | nindent 4 }}
    kubescape.io/tier: "core"
data:
  matchingRules.json: |
    {{ mustToJson .Values.continuousScanning.matchingRules }}
