kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.continuousScanning.configMapName }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.ksLabel }}
    tier: {{ .Values.global.namespaceTier }}
    kubescape.io/ignore: "true"
    kubescape.io/tier: "core"
data:
  matchingRules.json: |
    {{ mustToJson .Values.continuousScanning.matchingRules }}
