{{- if .Values.configurations.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-kubescape-critical
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" "kubescape-critical" "tier" .Values.global.namespaceTier) | nindent 4 }}
value: {{ .Values.configurations.priorityClass.daemonset }}
globalDefault: false
description: "This priority class is for node-agent daemonset pods"
{{- end }}
