{{- if gt (len (.Values.imageScanning.privateRegistries.credentials | default list)) 0 }}
apiVersion: v1
kind: Secret
metadata:
  # Secret name must start with 'kubescape-registry-scan' for the operator to pick it up, change at your own risk
  name: kubescape-registry-scan-secrets
  namespace: {{ include "randoli-agent.namespace" . }}
  annotations:
    {{- include "kubescape-operator.annotations" (dict "Values" .Values) | nindent 4 }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" "kubescape-registry-scan-secrets" "tier" .Values.global.namespaceTier) | nindent 4 }}
type: Opaque
stringData:
  registriesAuth: |
    [
      {{- range $index, $cred := .Values.imageScanning.privateRegistries.credentials }}
      {
        "registry": "{{ $cred.registry }}",
        "username": "{{ $cred.username }}",
        "password": "{{ $cred.password }}",
        {{- if $cred.skipTlsVerify }}
        "skipTLSVerify": true,
        {{- end }}
        {{- if $cred.insecure }}
        "http": true,
        {{- end }}
        "auth_method": "credentials"
      }{{ if ne $index (sub (len $.Values.imageScanning.privateRegistries.credentials) 1) }},{{ end }}
      {{- end }}
    ]
{{- end }}
