apiVersion: v2
name: security-scans
description: Randoli wrapper chart for the Kubescape Operator (v1.40.1)
type: application
version: 1.40.1
appVersion: "1.40.1"
dependencies:
  - name: kubescape-operator
    version: 1.40.1
    repository: https://kubescape.github.io/helm-charts/
