apiVersion: v2
name: security-scans
description: Randoli wrapper chart for the Kubescape Operator (v1.29.6)
type: application
version: 1.29.6
appVersion: "1.29.6"
dependencies:
  - name: kubescape-operator
    version: 1.29.6
    repository: https://kubescape.github.io/helm-charts/
