{{- $components := fromYaml (include "components" .) }}
{{- if and .Values.global.networkPolicy.enabled $components.synchronizer.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.synchronizer.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.synchronizer.name }}
    tier: {{ .Values.global.namespaceTier }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.synchronizer.name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      tier: {{ .Values.global.namespaceTier }}
  policyTypes:
    - Ingress
  {{- if .Values.global.networkPolicy.createEgressRules }}
    - Egress
  egress:
      # - synchronizer server
    - ports:
        - port: 8443
          protocol: TCP
  {{- end }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kubecop
              app.kubernetes.io/name: kubecop
      ports:
        - port: {{ .Values.synchronizer.service.port }}
          protocol: TCP
{{- end }}
