{{- $components := fromYaml (include "components" .) }}
{{- if $components.synchronizer.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.synchronizer.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.synchronizer.name "tier" .Values.global.namespaceTier) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.synchronizer.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.synchronizer.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
{{- end }}
