{{- $components := fromYaml (include "components" .) }}
{{- if $components.synchronizer.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.synchronizer.name }}
  namespace: {{ include "randoli-agent.namespace" . }}
  labels:
    {{- include "kubescape-operator.labels" (dict "Chart" .Chart "Release" .Release "Values" .Values "app" .Values.synchronizer.name "tier" .Values.global.namespaceTier) | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["create", "get", "update", "watch", "list", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["create", "get", "update", "watch", "list", "patch", "delete"]
{{- end }}
