{{- $components := fromYaml (include "components" .) }}
  {{- if $components.synchronizer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.synchronizer.name }}
  namespace: {{ include "app-insights-agent.namespace" . }}
  labels:
    app: {{ .Values.synchronizer.name }}
    kubescape.io/ignore: "true"
spec:
  type: {{ .Values.synchronizer.service.type }}
  ports:
    - port: {{ .Values.synchronizer.service.port }}
      targetPort: {{ .Values.synchronizer.service.targetPort }}
      protocol: {{ .Values.synchronizer.service.protocol }}
  selector:
    app: {{ .Values.synchronizer.name }}
  {{- end }}
